# Generated by Django 4.2.8 on 2023-12-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
