# Generated by Django 4.2.8 on 2023-12-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created']},
        ),
    ]
